# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, versions ]
  pull_request:
    branches: [ main, versions ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      reason:
        # Friendly description to be shown in the UI instead of 'name'
        description: "reason to run"
        # Default value if no value is explicitly provided
        default: "manual test rebuild"
        # Input has to be provided for the workflow to run
        required: true


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn preci
    - run: yarn ci
    - run: yarn build
      env:
        DRUPAL_CLIENT_ID: ${{ secrets.DRUPAL_CLIENT_ID }}
        DRUPAL_CLIENT_SECRET: ${{ secrets.DRUPAL_CLIENT_SECRET }}
        DRUPAL_FRONT_PAGE: ${{ secrets.DRUPAL_FRONT_PAGE }}
        DRUPAL_PREVIEW_SECRET: ${{ secrets.DRUPAL_PREVIEW_SECRET }}
        DRUPAL_SITE_ID: ${{ secrets.DRUPAL_SITE_ID }}
        NEXT_IMAGE_DOMAIN: ${{ secrets.NEXT_IMAGE_DOMAIN }}
        NEXT_PUBLIC_DRUPAL_BASE_URL: ${{ secrets.NEXT_PUBLIC_DRUPAL_BASE_URL }}
        NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID }}
        NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
        NEXT_PUBLIC_YM_ID: ${{ secrets.NEXT_PUBLIC_YM_ID }}
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
